### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'renderScale'

### ISSUE THREAD

**Issue by wetcork** [123aezakmi123/zanichelli_kitaboo_downloader#1]
Traceback (most recent call last):
  File "zanichelli_ebooks_downloader.py", line 77, in <module>
    download()
  File "zanichelli_ebooks_downloader.py", line 45, in download
    renderPDF.drawToFile(drawing, os.path.join(dir, "page" + str("%04d" % cont) + ".pdf"))
  File "D:\SDK\Python374\lib\site-packages\reportlab\graphics\renderPDF.py", line 290, in drawToFile
    d = renderScaledDrawing(d)
  File "D:\SDK\Python374\lib\site-packages\reportlab\graphics\renderbase.py", line 172, in renderScaledDrawing
    renderScale = d.renderScale
AttributeError: 'NoneType' object has no attribute 'renderScale'

**Comment by wetcork** [comment]
resolved

**Comment by ghost** [comment]
Hey, I know its a bit late, but do u mind telling me how you resolved the issue?
